### PR TITLE
Using multiple catalogs

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs I added the two extra `csw` endpoints, but that did not help. I guess we have some metadata issue somewhere.

### CODE REVIEW

**Comment by ocefpaf** [comment]
See [`cell [4]`](http://nbviewer.jupyter.org/github/ocefpaf/boston_light_swim/blob/1e15d3ca339a21db5e05b4680c0883014272cad6/00-fetch_data.ipynb
) for the multiple endpoints and here is the log:

```
03:34:35 INFO: ********************* Catalog information **********************
03:34:38 INFO: URL: http://www.ngdc.noaa.gov/geoportal/csw
03:34:38 INFO: CSW version: 2.0.2
03:34:38 INFO: Number of datasets available: 1
03:34:38 INFO: ***************************** CSW ******************************
03:34:38 INFO: HYbrid Coordinate Ocean Model (HYCOM): Global
03:34:38 INFO: ***************************** SOS ******************************
03:34:38 INFO: ***************************** DAP ******************************
03:34:38 INFO: http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html
03:34:39 INFO: URL: http://data.ioos.us/csw
03:34:39 INFO: CSW version: 2.0.2
03:34:39 INFO: Number of datasets available: 1
03:34:39 INFO: ***************************** CSW ******************************
03:34:39 INFO: HYbrid Coordinate Ocean Model (HYCOM): Global
03:34:39 INFO: ***************************** SOS ******************************
03:34:39 INFO: ***************************** DAP ******************************
03:34:39 INFO: http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html
03:34:41 INFO: URL: http://geoport.whoi.edu/csw
03:34:41 INFO: CSW version: 2.0.2
03:34:41 INFO: Number of datasets available: 0
03:34:41 INFO: ***************************** CSW ******************************
03:34:41 INFO: ***************************** SOS ******************************
03:34:41 INFO: ***************************** DAP ******************************
03:34:41 INFO: http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html
03:34:44 INFO: ************************* Filtered DAP *************************
03:34:44 INFO: http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global.html
```

**Comment by ocefpaf** [comment]
@rsignell-usgs I am running the notebooks now using the full service string like this:

```python
def service_urls(records, services=['urn:x-esri:specification:ServiceType:odp:url']):
    """
    Extract service_urls of a specific type (DAP, SOS for example) from csw records.
    """
    urls = []
    for service in services:
        for key, rec in records.items():
            url = next((d['url'] for d in rec.references if
                        d['scheme'] == service), None)
            if url is not None:
                urls.append(url)
        urls = sorted(set(urls))
    return urls
```

Note that we check for the string in the `['scheme']` field of each reference. Is that the best we can do right now?

Ping @kwilcox who might have a better idea on how to do this.

**Comment by rsignell-usgs** [comment]
Yes, that is exactly what we need to do.

**Comment by rsignell-usgs** [comment]
I cannot merge here.

**Comment by ocefpaf** [comment]
There will be a few more changes. I'll merge it in a few hours.
Em 10/06/2016 17:48, "Rich Signell" <notifications@github.com> escreveu:

**Comment by ocefpaf** [comment]
@rsignell-usgs I made the modifications but could not run the notebook due to a very slow connection. So I am committing a blank version and, hopefully, you can run that locally without major problems.

**Comment by ocefpaf** [comment]
The `csw` search is finding the two missing models, but it is hard to filter using the `scheme` key since that is filled as `'None'`:

```python
￼
rec.references
Out[30]:
[{'scheme': 'WWW:LINK',
  'url': 'http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc.html'},
 {'scheme': 'None',
  'url': 'http://www.ncdc.noaa.gov/oa/wct/wct-jnlp-beta.php?singlefile=http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc'},
 {'scheme': 'None',
  'url': 'http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc'},
 {'scheme': 'None',
  'url': 'http://www.smast.umassd.edu:8080/thredds/fileServer/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc'}]
```

**Comment by rsignell-usgs** [comment]
@ocefpaf, okay, their TDS is using an old version of ncISO.   I will see if they can update. 
Yet another reason why Docker will help save our butts in the future!

**Comment by rsignell-usgs** [comment]
@ocefpaf , okay, the SMAST TDS is updated, and seems to be producing the `ServiceType:OPeNDAP:OPeNDAP

**Comment by ocefpaf** [comment]
We are finding more models now :tada: 

But something changed in the modela and the noebook cannot find the time dimension, so the interpolation is returning all `NaNs` I am investigating this. (`CF+iris` should take care of this, but maybe our logic to find the time `coord` has a bug.)

**Pull request merged**
