### PR TITLE
Updated environment and notebook

### LINKED ISSUE #19: Update the notebook and binder
@rsignell-usgs I need to modify the notebook with a lot of new syntax changes in `iris` and `pandas`before updating the `binder`. So don't use this until then!

(Doing it now, should be OK in a few hours.)

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #19

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Woohoo!  Should this be a "release"?

**Comment by ocefpaf** [comment]
> Woohoo! Should this be a "release"?

Almost there. I am running the binder now and I noticed that it did not picked up the latest utilities. Not sure why :confused:

**Comment by rsignell-usgs** [comment]
Ah, I just verified this also.

**Comment by ocefpaf** [comment]
The Python 2.7 Linux binaries did not make it into the channel:

http://anaconda.org/IOOS/utilities/files

**Comment by ocefpaf** [comment]
I am debugging this now. Hold on...

**Pull request merged**
